import { mkdir,readFile,stat,writeFile,cp,rm } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import YAML from 'yaml'
import { ManifestSchema,VisualIRSchema } from '@ui-rebuild/contracts'
import { OpenAICompatibleModelAdapter,OpenAICompatibleTransport } from '@ui-rebuild/model-adapter'
import type { ModelImage } from '@ui-rebuild/model-adapter'

export async function loadManifest(root:string){return ManifestSchema.parse(YAML.parse(await readFile(path.join(root,'manifest.yaml'),'utf8')))}
export async function loadIR(root:string){return VisualIRSchema.parse(JSON.parse(await readFile(path.join(root,'visual-ir.json'),'utf8')))}
export async function modelImage(file:string):Promise<ModelImage>{const input=await readFile(file),metadata=await sharp(input).metadata(),format=metadata.format;if(!metadata.width||!metadata.height||!['png','jpeg','webp'].includes(format??''))throw new Error(`Unsupported model image: ${file}`);return{mediaType:`image/${format}` as ModelImage['mediaType'],base64:input.toString('base64'),width:metadata.width,height:metadata.height}}
export function modelAdapter(){const baseUrl=process.env.UI_REBUILD_MODEL_BASE_URL,model=process.env.UI_REBUILD_MODEL;if(!baseUrl||!model)throw new Error('Local multimodal model is not configured. Set UI_REBUILD_MODEL_BASE_URL and UI_REBUILD_MODEL.');return new OpenAICompatibleModelAdapter(new OpenAICompatibleTransport({baseUrl,model,apiKey:process.env.UI_REBUILD_MODEL_API_KEY}))}
export async function writeGenerated(appRoot:string,files:Readonly<Record<string,string>>){for(const [relative,content] of Object.entries(files)){const target=path.resolve(appRoot,relative),safeRoot=path.resolve(appRoot);if(target!==safeRoot&&!target.startsWith(`${safeRoot}${path.sep}`))throw new Error(`Generated file escapes app: ${relative}`);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,content)}}
export class DirectorySnapshotWorkspace{constructor(private readonly root:string,private readonly snapshots:string){}async createSnapshot(label:string){const id=`${label}-${crypto.randomUUID()}`,target=path.join(this.snapshots,id);await mkdir(this.snapshots,{recursive:true});await cp(this.root,target,{recursive:true,filter:source=>!source.includes(`${path.sep}node_modules${path.sep}`)&&!source.includes(`${path.sep}dist${path.sep}`)});return id}async restoreSnapshot(id:string){if(!/^[A-Za-z0-9._-]+$/u.test(id))throw new Error('Invalid snapshot id');const source=path.join(this.snapshots,id);await stat(source);for(const name of ['src']){await rm(path.join(this.root,name),{recursive:true,force:true});await cp(path.join(source,name),path.join(this.root,name),{recursive:true})}}async write(file:string,content:string){const target=path.resolve(this.root,file),safe=path.resolve(this.root);if(!target.startsWith(`${safe}${path.sep}`))throw new Error(`Patch escapes app: ${file}`);await mkdir(path.dirname(target),{recursive:true});await writeFile(target,content)}}
