import { mkdir, readFile, realpath, stat, writeFile, cp, rm, lstat } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import YAML from 'yaml'
import { ManifestSchema,validateManifestFiles,VisualIRSchema } from '@ui-rebuild/contracts'
import { OpenAICompatibleModelAdapter,OpenAICompatibleTransport } from '@ui-rebuild/model-adapter'
import type { ModelImage } from '@ui-rebuild/model-adapter'

export async function loadManifest(root:string){const manifest=ManifestSchema.parse(YAML.parse(await readFile(path.join(root,'manifest.yaml'),'utf8')));await validateManifestFiles(manifest,root,async absolutePath=>{try{const details=await stat(absolutePath);return{exists:true,isFile:details.isFile(),realPath:await realpath(absolutePath)}}catch(error){if(error instanceof Error&&'code' in error&&error.code==='ENOENT')return{exists:false,isFile:false,realPath:null};throw error}},realpath);return manifest}
export async function loadIR(root:string){return VisualIRSchema.parse(JSON.parse(await readFile(path.join(root,'visual-ir.json'),'utf8')))}
export async function modelImageBuffer(input:Buffer,label:string):Promise<ModelImage>{const metadata=await sharp(input).metadata(),format=metadata.format;if(!metadata.width||!metadata.height||!['png','jpeg','webp'].includes(format??''))throw new Error(`Unsupported model image: ${label}`);return{mediaType:`image/${format}` as ModelImage['mediaType'],base64:input.toString('base64'),width:metadata.width,height:metadata.height}}
export async function modelImage(file:string):Promise<ModelImage>{return modelImageBuffer(await readFile(file),file)}
export function modelAdapter(){const baseUrl=process.env.UI_REBUILD_MODEL_BASE_URL,model=process.env.UI_REBUILD_MODEL;if(!baseUrl||!model)throw new Error('Local multimodal model is not configured. Set UI_REBUILD_MODEL_BASE_URL and UI_REBUILD_MODEL.');const trustedRemoteOrigins=(process.env.UI_REBUILD_MODEL_TRUSTED_ORIGINS??'').split(',').map(origin=>origin.trim()).filter(Boolean);return new OpenAICompatibleModelAdapter(new OpenAICompatibleTransport({baseUrl,model,apiKey:process.env.UI_REBUILD_MODEL_API_KEY,trustedRemoteOrigins}))}
async function assertNoLinkedAncestor(root:string,target:string){const safeRoot=path.resolve(root);let current=path.dirname(target);while(current!==safeRoot){try{if((await lstat(current)).isSymbolicLink())throw new Error(`Linked path is not writable: ${current}`)}catch(error){if(error instanceof Error&&'code' in error&&error.code==='ENOENT'){current=path.dirname(current);continue}throw error}current=path.dirname(current)}}
export async function writeGenerated(appRoot:string,files:Readonly<Record<string,string>>){const safeRoot=path.resolve(appRoot),entries=Object.entries(files).map(([relative,content])=>({relative,content,target:path.resolve(appRoot,relative)}));for(const {relative,target} of entries){if(target!==safeRoot&&!target.startsWith(`${safeRoot}${path.sep}`))throw new Error(`Generated file escapes app: ${relative}`);await assertNoLinkedAncestor(safeRoot,target);try{if((await lstat(target)).isSymbolicLink())throw new Error(`Linked file is not writable: ${relative}`)}catch(error){if(!(error instanceof Error&&'code' in error&&error.code==='ENOENT'))throw error}}for(const {target,content} of entries){await mkdir(path.dirname(target),{recursive:true});await writeFile(target,content)}}
export class DirectorySnapshotWorkspace{constructor(private readonly root:string,private readonly snapshots:string){}async createSnapshot(label:string){const id=`${label}-${crypto.randomUUID()}`,target=path.join(this.snapshots,id);await mkdir(this.snapshots,{recursive:true});await cp(this.root,target,{recursive:true,filter:source=>!source.includes(`${path.sep}node_modules${path.sep}`)&&!source.includes(`${path.sep}dist${path.sep}`)});return id}async restoreSnapshot(id:string){if(!/^[A-Za-z0-9._-]+$/u.test(id))throw new Error('Invalid snapshot id');const source=path.join(this.snapshots,id);await stat(source);for(const name of ['src']){await rm(path.join(this.root,name),{recursive:true,force:true});await cp(path.join(source,name),path.join(this.root,name),{recursive:true})}}async write(file:string,content:string){const target=path.resolve(this.root,file),safe=path.resolve(this.root);if(!target.startsWith(`${safe}${path.sep}`))throw new Error(`Patch escapes app: ${file}`);await assertNoLinkedAncestor(safe,target);await mkdir(path.dirname(target),{recursive:true});try{if((await lstat(target)).isSymbolicLink())throw new Error(`Linked patch file is not writable: ${file}`)}catch(error){if(!(error instanceof Error&&'code' in error&&error.code==='ENOENT'))throw error}await writeFile(target,content)}}
