import { VisualIRSchema,isSafeProjectRelativePath } from '@ui-rebuild/contracts'
import type { RegionNode,VisualIRInput } from '@ui-rebuild/contracts'
import { writeAssetRegistry } from './asset-registry.js'
import { assertHealthyGeneratedFiles } from './component-policy.js'
import { logicalPxToRpx,writeTokens } from './token-writer.js'
export interface GenerateOptions{logicalWidth:number;assets?:Array<{key:string;path:string}>}
const pascal=(v:string)=>{const r=v.split('-').map(p=>p[0]!.toUpperCase()+p.slice(1)).join('');if(!/^[A-Z][A-Za-z0-9]*$/u.test(r))throw new Error(`Unsafe component name: ${v}`);return r}
const escape=(v:string)=>v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;')
function safePath(v:string){return isSafeProjectRelativePath(v)&&/^src\/components\/[a-zA-Z0-9_./-]+\.vue$/u.test(v)}
function relative(from:string,to:string){const a=from.split('/').slice(0,-1),b=to.split('/');while(a.length>0&&b.length>0&&a[0]===b[0]){a.shift();b.shift()}return `${'../'.repeat(a.length)}${b.join('/').replace(/\.vue$/u,'')}`}
function component(region:RegionNode,children:RegionNode[],current:string,paths:ReadonlyMap<string,string>,width:number){const imports=children.map(c=>`import ${pascal(c.regionId)} from '${relative(current,paths.get(c.regionId)!)}'`).join('\n');const tags=children.map(c=>`    <${pascal(c.regionId)} />`).join('\n');return `<script setup lang="ts">\n${imports}\n</script>\n<template><view class="semantic-region" data-region-id="${region.regionId}" aria-label="${escape(region.displayName)}">\n${tags}\n</view></template>\n<style scoped lang="scss">.semantic-region{display:flex;flex-direction:column;gap:var(--ui-space-page);min-width:${logicalPxToRpx(region.bounds.width,width)};min-height:${logicalPxToRpx(region.bounds.height,width)};background:var(--ui-color-surface)}</style>\n`}
export function generatePage(input:VisualIRInput,o:GenerateOptions):Record<string,string>{const ir=VisualIRSchema.parse(input);if(!/^[a-z][a-z0-9-]*$/u.test(ir.pageId))throw new Error(`Unsafe pageId: ${ir.pageId}`);const files:Record<string,string>={},paths=new Map<string,string>(),names=new Set<string>(),componentPaths=new Set<string>();for(const r of ir.regions){const n=pascal(r.regionId);if(names.has(n))throw new Error(`Component name collision: ${n}`);names.add(n);const p=(r.componentPath??`src/components/${ir.pageId}/${n}.vue`).replaceAll('\\','/');if(!safePath(p))throw new Error(`Unsafe componentPath: ${p}`);if(componentPaths.has(p))throw new Error(`Duplicate componentPath: ${p}`);componentPaths.add(p);paths.set(r.regionId,p)}for(const r of ir.regions){const p=paths.get(r.regionId)!;files[p]=component(r,ir.regions.filter(c=>c.parentId===r.regionId),p,paths,o.logicalWidth)}const page=`src/pages/${ir.pageId}/index.vue`,roots=ir.regions.filter(r=>r.parentId===null),imports=roots.map(r=>`import ${pascal(r.regionId)} from '${relative(page,paths.get(r.regionId)!)}'`).join('\n'),tags=roots.map(r=>`    <${pascal(r.regionId)} />`).join('\n');files[page]=`<script setup lang="ts">\n${imports}\n</script>\n<template><view class="page-${ir.pageId}">\n${tags}\n</view></template>\n<style scoped lang="scss">.page-${ir.pageId}{min-height:100vh;padding:var(--ui-space-page);background:var(--ui-color-page)}</style>\n`;files['src/styles/tokens.scss']=writeTokens(ir.tokens,o.logicalWidth);files['src/assets/registry.ts']=writeAssetRegistry(o.assets??[]);assertHealthyGeneratedFiles(files);return files}
