import { writeFile,mkdtemp,mkdir } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { chromium } from 'playwright'
import { describe,expect,it } from 'vitest'
import { generateReport } from './generate-report.js'
import { parseFeedback } from './feedback.js'
const fixture={title:'个人中心评审',canvas:{width:396,height:842},images:{reference:'images/ref.png',actual:'images/actual.png',heatmap:'images/heat.png'},regions:[{regionId:'owner-services',displayName:'车主服务区',aliases:['爱车服务模块'],bounds:{x:20,y:300,width:350,height:200},score:{total:.87,geometry:2,color:1.2,ssim:.95,text:{score:.82,content:.7,position:.9,fontSize:1,color:null,missing:['¥99.00'],added:['<script>alert(1)</script>'],lowConfidence:['subtotal'],matches:[{reference:'Total',actual:'TOTAL',cost:.02,critical:false}],extraction:{provider:'model' as const,model:'gpt-test',cacheHit:true}}},componentPath:'src/components/profile/OwnerServices.vue',assetSlots:['service.refuel'],changes:['间距调整'],interactions:[{description:'打开服务页',confidence:.9}]}]}
describe('generateReport',()=>{it('renders semantic overlays, details and complete feedback controls',()=>{const value=generateReport(fixture);expect(value).toContain('data-region-button="owner-services"');expect(value).toContain('爱车服务模块');expect(value).toContain('data-field="renameTo"');expect(value).toContain('data-field="assets"');expect(value).toContain('内容 0.700');expect(value).toContain('缺失文字');expect(value).toContain('¥99.00');expect(value).toContain('缓存命中');expect(value).not.toContain('<script>alert(1)</script>')});it('rejects malicious ids and absolute paths',()=>{expect(()=>generateReport({...fixture,regions:[{...fixture.regions[0]!,regionId:'x" onclick="alert(1)'}]})).toThrow();expect(()=>generateReport({...fixture,images:{...fixture.images,reference:'//server/ref.png'}})).toThrow()});it('validates full feedback',()=>expect(parseFeedback([{regionId:'owner-services',renameTo:'车主服务',aliases:['爱车'],assetOverrides:{'service.refuel':'assets/refuel.svg'}}])).toEqual([{regionId:'owner-services',renameTo:'车主服务',aliases:['爱车'],assetOverrides:{'service.refuel':'assets/refuel.svg'}}]));it('opens through file protocol and switches regions',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'ui-report-'));await mkdir(path.join(root,'images'));const pixel=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAFgwJ/lYNqWQAAAABJRU5ErkJggg==','base64');await Promise.all(['ref.png','actual.png','heat.png'].map(name=>writeFile(path.join(root,'images',name),pixel)));await writeFile(path.join(root,'report.html'),generateReport(fixture));const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();await page.goto(`file:///${path.join(root,'report.html').replaceAll('\\','/')}`);const button=page.locator('[data-region-button="owner-services"]');await expect(button.count()).resolves.toBe(1);await button.press('Enter');expect(await button.getAttribute('aria-pressed')).toBe('true')}finally{await browser.close()}},15000)})
